Repository sberdevices/smart_app_framework, pull requests merged in 2022-01, with the labels that each got.

#182 refactored test_date_determining.py module
  setup.py
  tests/core_tests/test_utils/test_date_determining.py
Labels: invalid

#186 fix logger error
  .github/workflows/python-package.yml
  core/logging/logger_utils.py
  core/logging/masker.py
  tests/core_tests/test_utils/test_logger.py
Labels: bug, enhancement

#183 Feature/rtdm support
  smart_kit/action/http.py
  smart_kit/message/get_to_message.py
  smart_kit/resources/__init__.py
  smart_kit/start_points/main_loop_kafka.py
Labels: enhancement
