Repository sberdevices/smart_app_framework, pull requests merged in 2022-02, with the labels that each got.

#172 disabling specific metrics by matching names
  core/db_adapter/aioredis_adapter.py
  core/db_adapter/aioredis_sentinel_adapter.py
  core/db_adapter/db_adapter.py
  core/monitoring/monitoring.py
  scenarios/scenario_descriptions/form_filling_scenario.py
  scenarios/scenario_descriptions/tree_scenario/tree_scenario.py
  smart_kit/start_points/base_main_loop.py
  smart_kit/template/static/configs/template_config.yml
  smart_kit/utils/monitoring.py
  tests/core_tests/monitoring_test/test_monitoring.py
Labels: enhancement

#195 added init message_handlers to main init
  smart_kit/resources/__init__.py
Labels: bugfix

#192 Поправить пакетный прогон для возможности проверки рандомного ответа
  smart_kit/template/static/references/tests/hello_scenario_tests.json
  smart_kit/utils/diff.py
Labels: enhancement

#196 DPNLPF-1497 added singleton settings for access to template settings
  core/utils/singleton.py
  smart_kit/configs/settings.py
Labels: integration

#184 change type check for default list and dict
  core/utils/masking_message.py
Labels: enhancement

#181 PNLP-3245 before_action and reset context action
  scenarios/actions/action.py
  smart_kit/models/dialogue_manager.py
  smart_kit/resources/__init__.py
  smart_kit/template/static/references/actions/actions.json
  tests/smart_kit_tests/models/test_dialogue_manager.py
Labels: enhancement

#193 DPNLPF-1460 client_profile_actions
  core/basic_models/actions/client_profile_actions.py
  smart_kit/resources/__init__.py
  smart_kit/template/static/configs/template_config.yml
  tests/core_tests/basic_scenario_models_test/action_test/test_action.py
Labels: enhancement, need approve

#200 Base http action
  smart_kit/action/base_http.py
  smart_kit/action/http.py
  tests/smart_kit_tests/action/test_base_http_action.py
  tests/smart_kit_tests/action/test_http.py
Labels: need approve

#194 Removed nested level of message in HttpTextNormalizer
  smart_kit/text_preprocessing/http_text_normalizer.py
Labels: bugfix

#190 DPNLPF-1389: logging fixes for log storing update
  core/logging/logger_utils.py
  core/model/base_user.py
  scenarios/user/user_model.py
  smart_kit/handlers/handle_respond.py
  smart_kit/management/app_manager.py
  smart_kit/start_points/base_main_loop.py
  smart_kit/start_points/main_loop_async_http.py
  smart_kit/template/static/configs/logging_config.yml
Labels: enhancement, integration, need approve
